tages:
  - deploy
  - dev

before_script:
  - echo before script is run 
  
test:
  stage: test
  tags:
    - dev
  script:
    - echo run test on dev-meetup

dev:
  stage: deploy
  tags:
    - dev
  script:
    - echo start deploy on dev server
    - git pull origin test
    - docker-compose up
  only:
    - dev

deploy:
  stage: deploy
  tags: 
    - meetup-prod
  script:
    - docker-compose -f docker-compose.yml stop server
    - git pull 
    - docker-compose -f docker-compose.yml down
    - docker-compose -f docker-compose.yml build server
    - docker-compose -f docker-compose.yml up -d 
    - docker-compose -f docker-compose.yml restart nginx
  only:
    - master

