image: golang:latest

stages:
  - test
  - deploy 

test:
  stage: test
  tags:
    - dev
  script:
    - echo testing
    - go test -v ./...

deploy-to-dev:
  stage: deploy  
  script:
    - echo deploy on dev server
    - make down
    - make run
  only:
    - developer
  tags:
    - dev

deploy-to-prod:
  stage: deploy
  tags: 
    - meetup-prod
  only:
    - master
  script:
    - echo deploy on prod server
    - make down
    - make run

# push -> test -> build image docker -> push to dockerhub -> download and launch image