image: docker

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

#test:
#  stage: test
#  tags:
#    - dev-server
#    - prod-server
#  variables:
#    GIT_CLEAN_FLAGS: -x -f -e data/**
#  script:
#    - echo test is started
#    - go test -v ./...

build:
  stage: build
  tags:
    - dev-server
  variables:
    GIT_CLEAN_FLAGS: -x -f -e mongo/**
  script:
    - docker image prune -f
    - docker-compose stop server && docker-compose rm -f server
    - docker-compose build server

dev_server:
  stage: deploy
  script:
    - docker-compose up -d server
  only:
    - developer
  tags:
    - dev-server

deploy-to-prod:
  stage: deploy
  tags:
    - prod-server
  only:
    - master
  script:
    - echo deploy on prod server