version: '3.4'

services:
  nginx:
    container_name: region_nginx
    image: nginx:1.16-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/html/static
    ports:
      - "80:80"
    depends_on:
      - server
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  server:
    container_name: region_server
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - configs/config.env
    volumes:
      - ./:/app:z
    depends_on:
      - mongo
    ports:
      - "8000:8000"

  mongo:
    container_name: region_mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      # MONGO_DATA_DIR: json
    volumes:
      - ./mongo/db:/data/db