version: '3.4'

services:

    server:
        container_name: server
        build: ./
        command: ./app
        ports: 
            - 8000:8000
        depends_on: 
            - mongo

    nginx:
        container_name: nginx
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        ports:
            - 80:80
            - 443:443

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: mongo
            MONGO_DATA_DIR: database
#        volumes:
#            - database:/data/db

#volumes:
#    database:
#        external: true
#    portainer_data: