version: '3.4'

services:

    server:
        container_name: server
        build: ./
        command: ./app
        ports: 
            - 8000:8000
        depends_on: 
            - mongo
            - mongo-express

    nginx:
        container_name: nginx
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        ports:
            - 80:80
            - 443:443

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: mongo
            MONGO_DATA_DIR: json
#        volumes:
#            - db:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
            ME_CONFIG_MONGODB_ADMINPASSWORD: mongo

#volumes:
#    database:
#    portainer_data: