version: '3.4'

services:
    nginx:
        container_name: region_nginx
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        restart: always
        volumes:
            - ./static:/var/www/html/static
        ports:
            - 80:80
        depends_on:
            - server
            - mongo-express
        command: "nginx -g 'daemon off;'"

    server:
        container_name: region_server
        build: ./
        volumes:
            - ./:/app:z
        depends_on:
            - mongo
            - mongo-express
        ports:
            - 8000:8000

    mongo:
        container_name: region_mongo
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: mongo
            # MONGO_DATA_DIR: json
        volumes:
            - ./mongo/db:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on: 
            - mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
            ME_CONFIG_MONGODB_ADMINPASSWORD: mongo

#volumes:
#    database:
#    portainer_data: